### PR TITLE
Added role restrictions

### PR DESCRIPTION
**Pull request by bigdonabele**
Added medics to restricted list for medic loadout

### CODE REVIEW

**Comment by jbrown215** [comment]
Can you test your change by:
1. Loading in as a non-medic and confirming that the class will not load
2. Loading in as each of the whitelisted roles and confirming that the class will load

Make sure you're running the mission in an MP environment!

If that works then we'll merge it in!

**Comment by bigdonabele** [comment]
Will also be adding and testing the following roles to "Medic" loadout, as well as "UH-60 Pilot", and "AH-64 Pilot" roles

"Regiment Commander@Regiment Headquarters", "Regiment XO@Regiment Headquarters", "Regiment CSM@Regiment Headquarters"

**Comment by bigdonabele** [comment]
Have tested the changes in a MP environment, with also changes in the above commit.  They are working as expected when tested locally.

**Review by jbrown215 — APPROVED** [review]
Sweet. In total you added:
1. Restrictions to the medic class
2. Restrictions to the crewman class
3. Added Regiment HQ roles to every whitelist

Looks good to me!

**Pull request merged**
